name: Backend CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./challedger-backend
        run: npm install

      - name: Run tests
        working-directory: ./challedger-backend
        run: npm test
