name: Frontend CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./challedger-frontend
        run: npm install

      - name: Run Tests
        working-directory: ./challedger-frontend
        run: npm test -- --watchAll=false

      - name: Run Build
        working-directory: ./challedger-frontend
        run: npm run build